### ISSUE TITLE
generateDG2DEM issue

### ISSUE THREAD

**Issue by ishikaj12** [ci1xgk/Fellowship_Webpage#13]
Hello, 

I've been working on preparing the Merewether test case to figure out how to work the LISFLOOD-FP model, and have made it to the step of generating the dem1x and dem1y files from the .demraw file (https://www.seamlesswave.com/Merewether2-4.html)

Whenever I try and run the command of `..\generateDG2DEM.exe merewether-0p175m.par`, I end up getting this error. 

<img width="1060" alt="Screen Shot 2023-05-18 at 1 35 42 PM" src="https://github.com/ci1xgk/Fellowship_Webpage/assets/77066462/f013b7ba-36d6-4db7-8dea-084c548aec85">

Would very much appreciate any help or ideas, thank you!

**Comment by bian0801** [comment]
"Hello, I'm encountering the same issue. It seems the GPU version of Lisflood wasn't successfully compiled, yet the GPU parameters are specified in the par file. I haven't been able to resolve this problem. Have you found a solution? Could you please share the method you used?"  

This translation maintains the technical context while expressing the troubleshooting inquiry naturally in English. Key elements preserved:  
1. GPU version compilation failure  
2. Parameter file (par file) configuration conflict  
3. Request for solution details  
4. Appropriate technical terminology retention (par file, GPU parameters)
