### ISSUE TITLE
Merewether Dataset

### ISSUE THREAD

**Issue by rarygit** [ci1xgk/Fellowship_Webpage#4]
Hi @ci1xgk and thanks for your team's effort in providing a clear and comprehensive description to begin modelling with LISFLOOD-FP v8.  The videos have been particularly helpful.

Having successfully compiled the lisflood binary on Ubuntu 20.04, I proceeded to follow the Merewether Case Study.
Unfortunately there are no Merewether input files as described below: 

> "Then place the input files (available in the testing\UoS\T04 directory of LISFLOOD-FP-trunk repository) inside the merewether directory as shown in the figure below"

[https://www.seamlesswave.com/Merewether3.html](url)

And not listed in the directories here:
[https://zenodo.org/record/4073011](url)

To continue following the tutorial video, would it be possible to post a link to the Merewether input files? 
Alternatively upload them to Zenodo or to GitHub?
Thanks!

**Comment by ci1xgk** [comment]
Hi there, we will uploading the raster dem for this test soon an you will be able to find it on this repository; 

https://zenodo.org/record/4645480#.YN7c0OhKiUl

It might be a couple of days until available. 

Best,
Georges

**Comment by rarygit** [comment]
Hi @ci1xgk - thanks for the quick reply!

Will this be just the raster dem, or will it include all the merewether input/output files as well?

I will check the zenodo link in a couple of days - thanks for that!

**Comment by msharifian** [comment]
Hi @rarygit, 

The "[Running the code, outputs and visualisation](https://github.com/ci1xgk/Fellowship_Webpage/blob/master/Merewether3.md)" section is now updated with the links to the input files.

Cheers

**Comment by rarygit** [comment]
Hi @msharifian

Thanks for updating the links to the input files and DEM on Zenodo!

I now have them and will continue with the Tutorial

Ciao!
